function(detectOS target)
if (APPLE)
  target_compile_definitions(${target} PUBLIC TONIC_PLAT_MACOS)
elseif (WIN32)
  target_compile_definitions(${target} PUBLIC TONIC_PLAT_WINDOWS)
else ()
  target_compile_definitions(${target} PUBLIC TONIC_PLAT_LINUX)
endif()
endfunction()

macro(detectBuildType target)
if (CMAKE_BUILD_TYPE STREQUAL "Release")
  target_compile_definitions(${target} PUBLIC TONIC_CONFIG_RELEASE)
elseif (CMAKE_BUILD_TYPE STREQUAL "Debug")
  target_compile_definitions(${target} PUBLIC TONIC_CONFIG_DEBUG)
elseif (CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
  target_compile_definitions(${target} PUBLIC TONIC_CONFIG_RELEASE)
elseif (CMAKE_BUILD_TYPE STREQUAL "MinSizeRel")
  target_compile_definitions(${target} PUBLIC TONIC_CONFIG_RELEASE)
endif()
endmacro()