#define LIST_OF_UNIFORM_PRIMS \
DEFINE_PRIM(float, f) \
DEFINE_PRIM(unsigned int, ui) \
DEFINE_PRIM(int, i)

#define LIST_OF_UNIFORM_MATRICES \
DEFINE_MAT(2) \
DEFINE_MAT(2x3) \
DEFINE_MAT(2x4) \
DEFINE_MAT(3x2) \
DEFINE_MAT(3) \
DEFINE_MAT(3x4) \
DEFINE_MAT(4x2) \
DEFINE_MAT(4x3) \
DEFINE_MAT(4) \

LIST_OF_UNIFORM_PRIMS
LIST_OF_UNIFORM_MATRICES

#undef LIST_OF_UNIFORM_PRIMS
#undef LIST_OF_UNIFORM_MATRICES
